name: CF TEST
on:
  workflow_dispatch:

jobs:
  analyze_domain:
    runs-on: ubuntu-latest
    steps:
      - name: serve
        run: |
          docker run -d -p 5800:5800 domistyle/tor-browser &
      - name: Run establish a cf tunnel
        run: |
          npx untun@latest tunnel http://localhost:5800 -y
      - name: sleep
        run: sleep 100000000000000000000000000
