name: Upload File to GoFile

on:
  workflow_dispatch:
    inputs:
      dl_url:
        description: 'Download URL'
        required: true
      file_name:
        description: 'File Name'
        required: true

jobs:
  upload_to_gofile:
    runs-on: ubuntu-latest
    steps:
      - name: Download File
        run: aria2c -x 16 -o "${{ github.event.inputs.file_name }}" "${{ github.event.inputs.dl_url }}"
      
      - name: Get Server Name
        id: get_server
        run: |
          servers=$(curl -X GET 'https://api.gofile.io/servers')
          echo "::set-output name=server_name::$(echo $servers | jq -r '.data.servers[0].name')"

      - name: Upload File to GoFile
        run: |
          server_name="${{ steps.get_server.outputs.server_name }}"
          curl -X POST "https://${server_name}.gofile.io/contents/uploadfile" -F "file=@${{ github.event.inputs.file_name }}"
