name: Js Enum

on:
  workflow_dispatch:
    inputs:
      domain:
        description: 'Domain to analyze'
        required: true

jobs:
  analyze_domain:
    runs-on: ubuntu-latest
    steps:
      - name: Check and Extract Domain
        run: |
          if [[ ${{ github.event.inputs.domain }} == *://* ]]; then
            domain=$(echo "${{ github.event.inputs.domain }}" | sed 's/.*\/\///' | sed 's/\/.*//')
          else
            domain=${{ github.event.inputs.domain }}
          fi
          echo "Exporting domain as $domain"
          export domain=domain
          
      - name: Install Subfinder and HTTPX
        run: |
          go install -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest
          go install -v github.com/projectdiscovery/httpx/cmd/httpx@latest
          go install github.com/projectdiscovery/katana/cmd/katana@latest

      - name: Gather Subdomains
        run: |
          subfinder -d $domain -all -recursive > subdomains.txt

      - name: Check Subdomains Alive
        run: |
          cat subdomains.txt | httpx -ports 80,8080,8000,8888 -threads 200 > subdomains_alive.txt

      - name: Find JavaScript Files
        run: |
          katana -list subdomains_alive.txt -d 5 -jc | grep ".js$" | uniq | sort >> js.txt

      - name: Clone SecretFinder and Install Dependencies
        run: |
          git clone https://github.com/m4ll0k/SecretFinder
          cd SecretFinder
          pip3 install -r requirements.txt
          cd ..

      - name: Find Secrets in JavaScript Files
        run: |
          cat js.txt | while read url; do python3 SecretFinder/SecretFinder.py -i $url -o cli >>jscreds.txt; done

      - name: Upload jscreds.txt to file.io
        run: |
          sudo apt install jq
          link=$(curl -F "file=@jscreds.txt" https://file.io | jq -r '.link')
          echo "$link"
