name: Sql Enum

on:
  workflow_dispatch:
    inputs:
      domain:
        description: 'Domain to analyze'
        required: true

jobs:
  analyze_domain:
    runs-on: ubuntu-latest
    steps:
      - name: Check and Extract Domain
        run: |
          if [[ ${{ github.event.inputs.domain }} == *://* ]]; then
            domain=$(echo "${{ github.event.inputs.domain }}" | sed 's/.*\/\///' | sed 's/\/.*//')
          else
            domain=${{ github.event.inputs.domain }}
          fi
          echo "Exporting domain as $domain"
          export domain=$domain

      - name: Setup ⚡️
        run: |
            git clone https://github.com/americo/sqlifinder
            cd sqlifinder
            pip3 install -r requirements.txt
      - name: Run Tool
        run: |
          cd sqlifinder
          python3 sqlifinder.py -d ${{ github.event.inputs.domain }} >>sqli.txt
      
      - name: Result
        run: |
          echo "Task has been completed :)"
          cat sqli.txt
      - name: Upload sqli.txt to file.io
        run: |
          sudo apt install jq
          link=$(curl -F "file=@sqli.txt" https://file.io | jq -r '.link')
          echo "$link"
